name: "Terraform and Kubernetes Integration"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Start Minikube inside GitHub Actions
      - name: Start Minikube
        run: minikube start --driver=docker

      # Verify Minikube is running
      - name: Check Minikube Status
        run: minikube status

      # Set up kubectl (Kubernetes CLI)
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

      # Authenticate with Kubernetes Cluster
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          minikube kubectl -- get nodes
          minikube update-context
          minikube kubectl config view --flatten > ~/.kube/config

      # Verify Kubeconfig
      - name: Verify Kubernetes Context
        run: |
          kubectl cluster-info
          kubectl get nodes

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.7"

      # Terraform init
      - name: Terraform Init
        run: terraform init

      # Terraform plan
      - name: Terraform Plan
        run: terraform plan

      # Terraform apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

